"""brand favicon and logo

Revision ID: 6c4063ede536
Revises: f7b8b5fafafc
Create Date: 2026-07-20 04:12:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c4063ede536'
down_revision = 'f7b8b5fafafc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favicon_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('logo_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('logo_path')
        batch_op.drop_column('favicon_path')
    # ### end Alembic commands ###
