"""initial schema

Revision ID: 84440bc14826
Revises: 
Create Date: 2026-07-19 02:49:52.961992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84440bc14826'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=120), nullable=False),
    sa.Column('company_description', sa.String(length=400), nullable=True),
    sa.Column('company_whatsapp', sa.String(length=20), nullable=False),
    sa.Column('company_email', sa.String(length=190), nullable=True),
    sa.Column('company_phone', sa.String(length=30), nullable=True),
    sa.Column('company_address', sa.String(length=255), nullable=True),
    sa.Column('color_primary', sa.String(length=9), nullable=False),
    sa.Column('color_secondary', sa.String(length=9), nullable=False),
    sa.Column('hero_title', sa.String(length=200), nullable=True),
    sa.Column('hero_subtitle', sa.String(length=400), nullable=True),
    sa.Column('hero_video_path', sa.String(length=255), nullable=True),
    sa.Column('hero_overlay_opacity', sa.Float(), nullable=False),
    sa.Column('hero_cta_primary_label', sa.String(length=80), nullable=True),
    sa.Column('hero_cta_secondary_label', sa.String(length=80), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testimonials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('company_name', sa.String(length=120), nullable=False),
    sa.Column('text', sa.String(length=600), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=190), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'EDITOR', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email_snapshot', sa.String(length=190), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_ref', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=190), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('segment', sa.String(length=100), nullable=True),
    sa.Column('preferred_locations', sa.String(length=255), nullable=True),
    sa.Column('budget_range', sa.String(length=60), nullable=True),
    sa.Column('status', sa.Enum('NOVO', 'EM_ANDAMENTO', 'CONTATADO', 'CONVERTIDO', 'ARQUIVADO', name='proposal_status'), nullable=False),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contacted_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contacted_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposals_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposals_public_ref'), ['public_ref'], unique=True)
        batch_op.create_index(batch_op.f('ix_proposals_status'), ['status'], unique=False)
        batch_op.create_index('ix_proposals_status_created', ['status', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.drop_index('ix_proposals_status_created')
        batch_op.drop_index(batch_op.f('ix_proposals_status'))
        batch_op.drop_index(batch_op.f('ix_proposals_public_ref'))
        batch_op.drop_index(batch_op.f('ix_proposals_email'))
        batch_op.drop_index(batch_op.f('ix_proposals_created_at'))

    op.drop_table('proposals')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('testimonials')
    op.drop_table('site_settings')
    op.drop_table('services')
    op.drop_table('partners')
    op.drop_table('gallery_items')
    # ### end Alembic commands ###
