"""hero media, theme colors, legal pages

Revision ID: f7b8b5fafafc
Revises: 84440bc14826
Create Date: 2026-07-19 21:50:58.518980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b8b5fafafc'
down_revision = '84440bc14826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hero_media_type', sa.String(length=10), nullable=False, server_default='video'))
        batch_op.add_column(sa.Column('hero_image_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('services_accent_color', sa.String(length=9), nullable=False, server_default='#FFB020'))
        batch_op.add_column(sa.Column('gallery_accent_color', sa.String(length=9), nullable=False, server_default='#FFB020'))
        batch_op.add_column(sa.Column('testimonials_accent_color', sa.String(length=9), nullable=False, server_default='#37D6C7'))
        batch_op.add_column(sa.Column('card_background_color', sa.String(length=9), nullable=False, server_default='#131A24'))
        batch_op.add_column(sa.Column('card_border_radius', sa.Integer(), nullable=False, server_default='12'))
        batch_op.add_column(sa.Column('privacy_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('terms_content', sa.Text(), nullable=True))

    # Remove os server_default após popular as linhas existentes: o valor
    # padrão passa a ser controlado apenas pela aplicação (SQLAlchemy),
    # evitando "mágica" escondida no schema do banco.
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.alter_column('hero_media_type', server_default=None)
        batch_op.alter_column('services_accent_color', server_default=None)
        batch_op.alter_column('gallery_accent_color', server_default=None)
        batch_op.alter_column('testimonials_accent_color', server_default=None)
        batch_op.alter_column('card_background_color', server_default=None)
        batch_op.alter_column('card_border_radius', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('terms_content')
        batch_op.drop_column('privacy_content')
        batch_op.drop_column('card_border_radius')
        batch_op.drop_column('card_background_color')
        batch_op.drop_column('testimonials_accent_color')
        batch_op.drop_column('gallery_accent_color')
        batch_op.drop_column('services_accent_color')
        batch_op.drop_column('hero_image_path')
        batch_op.drop_column('hero_media_type')

    # ### end Alembic commands ###
